spring:
  application:
    name: drawandguess
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  threads:
    virtual:
      enabled: true
  thymeleaf:
    check-template-location: false

logging:
  level:
    org:
      springframework:
        web:
          socket: INFO
        security: INFO